/**
 * @file	Enum_ShipPart.h
 * @brief   Enumeration with all possible ship's part/boat states
 */

/*
 * Copyright (c) 2025 Oleksandr "tAtaman" Bolbat
 */

#ifndef ENUM_SHIP_PART_H
#define ENUM_SHIP_PART_H


typedef enum ShipPart {
	CLOUD_CELL,
    WATER_CELL,
    BOAT_HORIZONTAL,
	BOAT_VERTICAL,
    MIDDLE_PART_HORIZONTAL,
    MIDDLE_PART_VERTICAL,
    BOW_HORIZONTAL,
    BOW_VERTICAL,
    END_HORIZONTAL,
    END_VERTICAL,
    DAMAGED_BOW_HORIZONTAL,
    DAMAGED_BOW_VERTICAL,
    DAMAGED_MIDDLE_PART_HORIZONTAL,
    DAMAGED_MIDDLE_PART_VERTICAL,
    DAMAGED_END_HORIZONTAL,
    DAMAGED_END_VERTICAL,
    DESTROYED_BOAT_HORIZONTAL,
    DESTROYED_BOAT_VERTICAL,
    DESTROYED_BOW_HORIZONTAL,
    DESTROYED_BOW_VERTICAL,
    DESTROYED_MIDDLE_PART_HORIZONTAL,
    DESTROYED_MIDDLE_PART_VERTICAL,
    DESTROYED_END_HORIZONTAL,
    DESTROYED_END_VERTICAL
} shipPart_e;


#endif
