/**
 * \file	Enum_ShipPart.h
 * \brief
 */

/*
 * Copyright (c) 2025 Oleksandr "tAtaman" Bolbat
 */

#ifndef ENUM_SHIP_PART_H
#define ENUM_SHIP_PART_H


typedef enum ShipPart {
	FREE_CELL,
    BOAT_HORIZONTAL,
	BOAT_VERTICAL,
    MIDDLE_PART_HORIZONTAL,
    MIDDLE_PART_VERTICLE,
    BOW_HORIZONTAL,
    BOW_VERTICLE,
    END_HORIZONTAL,
    END_VERTICLE,
    DAMAGED_BOW_HORIZONTAL,
    DAMAGED_BOW_VERTICLE,
    DAMAGED_MIDDLE_PART_HORIZONTAL,
    DAMAGED_MEDDLE_PART_VERTICLE,
    DAMAGED_END_HORIZONTAL,
    DAMAGED_END_VERTICLE,
    DESTROYED_SHIP_PART
} shipPart_e;


#endif
